sudo: required
language: node_js
node_js:
- '10'
before_install:
- yarn
script:
- yarn build
env:
  global:
  - secure: mpO9feh6BEX4XEfURgMnA7Y148JtksH9J29jezIAA04xxpZw+7wHOMiLFtEjcBi48M1K3SeF2x3efxR5gok5zer9qB9J7N0vwFf2EbecuI4RL6pcFNRcMay7QJHlbzubMtwi3cZKW/Uss/4QgrKRHmmi+EEKyNJqQBn9xT80WtVETb/NMu+VGQru6iLBJO/yqpDMGlzq8BvJ3WQLEUIa+0vQNEpjgfkqFIz9SOo0kz79mgjhXFaK15GFJ5Lngg4EdBc/xMhHcmOHTbYXg6LFpL4AJwuNqS9lZgFZ5fOTMGI51OMiVaImQbB06ddCHA3VLOuwVSHeB2LJ1Wb5SGboGU8Da+l/YbQd+nlR2xtb6W9qETDj3EHuiIDzwWR5ZHD9+qjiz1/D7p8o7wlALeWIfLXQPNzCFIjtqj3NEeBb1SHAOLv5DdAXkqEVfVdmE7WQecZbHo13fsV04wU43qyVAllQNpr2BZPaULMx87b4EWRL4H6aj4k6c7/U0/6KxnKmqrAN/n4YyaYtQXdwqAngh/a+U1eYviGX8NlkD9+UeM5np3+CUtflkQIiQDheBCS38w2Jei2TbKtG8cJhTf1zHPOzm1TneHHeDQUGLnAA2S3R5GYumvliYjCg7/cTdtPzjRCm4dbNJKQfWFk3Bj7Xr0hSX8/3FMLRy9Be4QP0BEk=
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  repo: JanssenZhang/JanssenZhang.github.io
  on:
    branch: master
