sudo: required
language: node_js
node_js:
- '10'

before_install:
- npm install

script:
- npm run build

deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: JayZHZ/JayZHZ.github.io
  github-token:
    secure: vogAON1yMmimqPx6v3Z2LEXCopnL4h17d0m1Jjx1EIJ5rON+f75j8aRBxhcnerhurWffuCi9QDHsIDllTQ7p7tHgkkRQ4c7XO5SyF2FvmNwcUMsxMbhbRY7+1Vyvgk7eOVa4OxiVj/ZcAvs3/yxtUUQuNRFnaT7qiJqHxqOILmrIHmzETMryfPkH3WsXLckJzQxFBrjQ495sp6hSA93SHvLw0AFxjHxZqnOuyv2RQiyElxYH3AI1UmndBRvQEXpFd/FO5/rPO3w9fAu3Nbi6t+tNVjcjiQNpykzI9gRtcjcWFtF9BINZWL1n6n5Aubrv8wVMTh521kyZeF91CzMKm0v1kV1/UxiWg58/fb1mBypjjTpvSvxM7ykw8skGjbUjwOtHKb+QabPexVGo8KyHE5Oxr6o+uwUQtSyxVnxcE/Rco+airVnCj+sKHvtkCdwu0rggCLtEOJjkl+x/4GTKzKCfb4SweKZDO+4wGefOsvVmdDOEAnsqWfpcBYc870RiU7blvv21yF7R7ftOfmBkwSZaykp9ZTDQl+BAdNxPexx/dTMfdL2sVh0VMnAgujm/TZiU3h90efCWEiAKIXlAabPRcNIzZon47IFzuGQu6JQtMjbmjdQiFp3YNkL9GHL4kJIqP0FQWbPqWfc2WscI/zcVu/CvIZGRca+V0MXgaFQ=
  keep-history: true
  on:
    branch: master
