sudo: required
language: node_js
node_js:
- '10'
before_install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: JayZHZ/JayZHZ.github.io
  github-token: "$REPO_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
  - secure: fEoD3G2FSbUoQca78mc8J+Zojikwgnko1FPaOFe9khfA6FRThSeuxnO166h2rTqO9/r4Y4c6ssaRjFVYl6iHysuppXoSrrxLqZaVeyuAWMlLIEBUDPnXTyWKmZ6nyBndHhIGvZgXGpBiha72E6CUnJHTifQfvF0j6a5WbHYljWUEBgw7WhXVB+HrTgRbw5THEanPFa7/L5WL8gIdVf99D2KKH9gcz9eLbWaHqJHlm5lmbOXicOf4oy229L/XCJm/rsiJ5A8rmlGE/tHlEQf7lRfHhT1a/PamqIpzMlSFPlqRZK8QYLqegHkoEtQOLBj+le4jrAjZwko4AG7F+3focTcm4OsAP0kM9kz2diqzF/eRq3+CXo2r24J4YCxUFlraMO4NkNapDENB/nc3/98uW7tXbf5Ahk2XjUCYoPah9pTDHkj/4+0TkjnrL9+13IFd/JB/Hfy/AwZXlyhT2GyTSkwVcAtjtLRI9FbsMJrDVe2Gh0q381eiXbf2fe42Zz2qFc0hmHMg5PG/Aw4QFpT5CpZzO2Clxxn/cQk1rinYX4gFpjFMDa5t04zQATwc6VBHtGKIAY2kwnd4qTQYieFb7/HHAv4ZyfWPZlEb5G6fOR8Y2GUSwp7W5mh1vKc7JF1COROBokez4l2zbgQDzDDQf5CSmODlOCUCekj7s/m7Eps=
